#!/usr/local/bin/bash


####################################
#
#
#  7unzip()   { if [ -n "$1" ]; then 7z x -t7z $1 -o. ; else echo "usage: $FUNCNAME <archive.7z>" ; fi }
#
#
####################################


echo

echo "7unzip Program"
echo "--------------"
echo

echo -n "Name of archive to extract (.7z): " ; read fileName


if [ -f "$fileName".7z ]
then
  7z x -t7z "$fileName".7z -o.

else
  echo
  echo "Invalid File Name.."
  echo

  exit 1

fi


