#!/usr/local/bin/bash


####################################
#
#
#  7z t
#
#
####################################


echo

echo "7zip Program"
echo "------------"
echo

echo -n "Name of archive to test (.7z): " ; read fileName


if [ -f "$fileName".7z ]
then
  7z t "$fileName".7z

else
  echo
  echo "Invalid File Name.."
  echo

  exit 1

fi


