#!/usr/local/bin/bash


####################################
#
#
#  alias 7zip='7z a -t7z'  # *.7z
#
#
####################################


echo

echo "7zip Program"
echo "------------"
echo

echo -n "Folder to archive: " ; read folderName
echo
echo -n "Name of archive (.7z): " ; read fileName


if [ -d "$folderName" ] && [ -n "$fileName" ]
then
  7z a -t7z "$fileName".7z  "$folderName"

else
  echo
  echo "Invalid input, exiting.."
  echo

  exit 1

fi


