#!/usr/local/bin/bash


####################################
#
#
#  7z l
#
#
####################################


echo

echo "7zip Program"
echo "------------"
echo

echo -n "Name of archive to show info (.7z): " ; read fileName


if [ -f "$fileName".7z ]
then
  7z l "$fileName".7z

else
  echo
  echo "Invalid File Name.."
  echo

  exit 1

fi


