#!/bin/bash


####################################
#
#
#  1.  tidy-html         // format html
#  2.  clean-keepass     // remove password
#  3.  remove line # 13  //
#
#
#  perl -pi -e 's/password">[^<]*/password">#####/g' "$1"
#
#
####################################


script=`basename $0`


if [ -n "$1" ]
then
  perl -pi -e 's/password">[^<]*/password">#####/g' "$1"
else
  echo "usage: $script <file>"
fi

