#!/usr/local/bin/bash


####################################
#
#
#  C:/Windows/System32/drivers/etc/hosts
#
#
####################################


echo

echo "Append to hosts file"
echo "--------------------"
echo

echo -n "Enter IP address of remote PC: " ; read ipAddress
echo
echo -n "Enter name of remote PC: " ; read name


/bin/cp  /etc/hosts  /tmp/hosts.txt

echo -e "\n"                      >>  /tmp/hosts.txt
echo    "###----------"           >>  /tmp/hosts.txt
echo    "$ipAddress       $name"  >>  /tmp/hosts.txt
echo    "###----------"           >>  /tmp/hosts.txt

echo

sudo cp /tmp/hosts.txt  /etc/hosts

