#!/bin/bash


####################################
#
#
#  /sbin/md5
#
#
####################################


if [ -n "$1" ]
then
  file1="$1"
  file2="${file1%.*}"

  str1=`cut -d' ' -f1 $file1`
  str2=`/sbin/md5 -q  $file2`


  if [ $str1 != $str2 ]
  then
    echo "WARNING: checksums do NOT Match"
  else
    echo "$file2": "OK"
  fi

else
  echo "usage:" $(basename $0) "<file.md5>"

fi

