#!/bin/bash


: '
//////////


#  scp <source-file> user@host:<path>
#  scp user@host:<path of source file> <local target for file>


//////////
'


if [ -n "$4" ]
then
  scp "$1"@"$2":"$3" "$4"

else
  echo "usage:" $(basename $0) "<user> <host> <path of source file> <local target for file>"

fi


