#!/bin/ash


####################################
#
#
#  7unzip()   { if [ -n "$1" ]; then 7z x -t7z $1 -o. ; else echo "usage: $FUNCNAME <archive.7z>" ; fi }
#
#
####################################


echo

echo "Unlzma extract with 7z"
echo "----------------------"
echo

echo -n "Name of archive to extract (.lzma): " ; read fileName


if [ -f "$fileName".lzma ]
then
  7z x -tlzma "$fileName".lzma -o.

else
  echo
  echo "Invalid File Name.."
  echo

  exit 1

fi


